# Project information
site_name: Sam Loves Coffee
site_url: https://samloves.coffee/
site_author: Samuel Cochrane
site_description: >-
  Hi, I'm Samuel Cochrane.
  I turn abstract data into information, make that information actionable, and make those actions the right ones.

# Repository
#repo_name: squidfunk/mkdocs-material
#repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: Copyright &copy; 2023 Samuel D.C.

# Configuration
theme:
  name: material
  custom_dir: material/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/lovecoffee.svg
  icon:
    logo: logo

nav:
  - Home: index.md
  

# Plugins
plugins:
  - awesome-pages:
      order: asc
      sort_type: natural
      order_by: title
  - blog:
      blog_dir: .
      post_url_format: "{slug}"
      post_readtime: false
  - link-marker
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - ezlinks:
      wikilinks: true
  - callouts
  - glightbox
  - embed_file:
      callouts: true
  - mkdocs-backlinks:
      ignored_pages: [ 'Tags', 'Home' ] 

# Hooks
hooks:
  - material/.overrides/hooks/translations.py
  - overrides/hooks/on_page_markdown.py
  - overrides/hooks/on_env.py
  - overrides/hooks/on_files.py
# Customization
extra:
  annotate:
    json: [.s2]
  generate_graph: false #generate the graph of the site
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SamuelCochrane/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/notamalemodel/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/cochrane-sam/


extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - assets/css/customization.css

extra_javascript:
  - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mdx_breakless_lists
  - nl2br # newline-to-break 
  - smarty
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
